---
- name: Add cgroups to /etc/fstab
  lineinfile:
    dest: /etc/fstab
    line: cgroup /sys/fs/cgroup cgroup defaults 0 0

- name: Define cgroup mount points
  copy:
    content: |
      mount {
        cpuacct = /cgroup/cpuacct;
        memory = /cgroup/memory;
        devices = /cgroup/devices;
        freezer = /cgroup/freezer;
        net_cls = /cgroup/net_cls;
        blkio = /cgroup/blkio;
        cpuset = /cgroup/cpuset;
        cpu = /cgroup/cpu;
      }
    dest: /etc/cgconfig.conf
    mode: 0644

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.22.3+k3s1 K3S_KUBECONFIG_MODE="0644" sh -s - --disable=traefik

- name: Wait for nodes to be ready
  shell: "/usr/local/bin/kubectl get nodes"
  register: nodes
  until: '" Ready "  in nodes.stdout'
  retries: 20
  delay: 5

- name: Install nginx Ingress
  command: /usr/local/bin/kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.5/deploy/static/provider/cloud/deploy.yaml
